version: '3.8'

services:
  sports-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sports-frontend
    restart: unless-stopped
    ports:
      - "3100:9000" # المنفذ الخارجي = 3100، الداخلي = 9000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "coolify.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.sports-frontend.rule=Host(`quattrogcc.ae`)"
      - "traefik.http.routers.sports-frontend.entrypoints=http,https"
      - "traefik.http.routers.sports-frontend.tls.certresolver=le"
      - "traefik.http.services.sports-frontend.loadbalancer.server.port=9000"

networks:
  default:
    name: coolify_default