version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sports-frontend
    restart: unless-stopped
    ports:
      - "3100:9000" # ربط المنفذ الخارجي (3100) بالداخلي (9000)
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: sports-frontend-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  node_modules: