server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # كل الطلبات إلى index.html عشان React Router يشتغل صح (Single Page App)
    location / {
        try_files $uri /index.html;
    }

    # منع استعراض المجلدات
    location ~ /\. {
        deny all;
    }
}
